drop trigger FUNC_FK_INSTRUCTOR;
drop table INSTRUCTOR cascade constraints;
drop table ADVICE cascade constraints;
drop table BUILDING cascade constraints;
drop table CLASSROOM cascade constraints;
drop table COURSE cascade constraints;
drop table COURSE_TEXTBOOK cascade constraints;
drop table DEPARTMENT cascade constraints;
drop table EMPLOYEE cascade constraints;
drop table HIRE cascade constraints;
drop table INSTRUCTOR cascade constraints;
drop table LAB cascade constraints;
drop table LECTURER cascade constraints;
drop table OFFICE cascade constraints;
drop table PEOPLE cascade constraints;
drop table PROFESSOR cascade constraints;
drop table RA cascade constraints;
drop table RA_WORK_ASSIGNMENT cascade constraints;
drop table ROOM cascade constraints;
drop table RUN cascade constraints;
drop table SECTION cascade constraints;
drop table SECTION_HAS_TA cascade constraints;
drop table STUDENT cascade constraints;
drop table STUDENT_PREREQUISITE cascade constraints;
drop table TA cascade constraints;
drop table TAKE cascade constraints;
drop table TRACK cascade constraints;
drop table TRACK_CORE_COURSE cascade constraints;
drop view Current_Courses;
drop view Department_heads;
drop view student_workers;
drop view students_with_prerequisites;